# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/trusty64'

  # Production machine
  config.vm.define :production do |production_config|
    production_config.vm.network :private_network, ip: '192.168.33.201'
  end
end