version: '2'
services:
  application:
    build: docker/application/
    volumes:
      - ./code:/var/www/symfony

  php:
    build: docker/php/
    expose:
      - 9000
    volumes_from:
      - application
    depends_on:
      - application

  frontend:
    build: docker/frontend/
    ports:
      - 80:80
      - 443:443
    links:
      - php
    depends_on:
      - php
      - application
    volumes_from:
      - application
    volumes:
      - ./docker/logs/frontend/:/var/log/nginx
