---
# This playbook is used to deploy our docker containers
# It pulls the images from the docker hub and makes sure
# they are started

# Install & start the application data container (with our application in /var/www/symfony)
- name: Install application data container
  docker:
    name: application
    image: slipke/ansible-docker-paper-application
    state: present
    pull: always

# Install the PHP-Container, open port 9000 for other services
# and use the volume from the application container
- name: Install php container
  docker:
    name: php
    image: php:5.5-fpm
    expose:
      - 9000
    volumes_from:
      - application
    state: started

# Install and start the frontend container. nginx is used as base image,
# port 80 is opened to public
- name: Install frontend container
  docker:
    name: frontend
    image: slipke/ansible-docker-paper-frontend
    ports:
      - 80:80
    links:
      - php:php
    volumes_from:
      - application
    state: started