##################
# Project settings
##################
project_name: "ansible-docker-paper"
site_fqdn: "{{ project_name }}.de"

base_path: "/var/www"
site_path: "{{ base_path }}/{{ project_name }}"

#####################
# Additional packages
#####################

# angstwad.docker_ubuntu
docker_group_members:
  - vagrant